### ISSUE TITLE
Update pyvan PyPi version (add github action?)

### ISSUE THREAD

**Issue by silvandeleemput** [ClimenteA/pyvan#17]
@ClimenteA thank you for all your quick replies so far! Could you release a new PyPi version of pyvan with the new changes? e.g. version 0.06?

Maybe you would be interested to add some github actions to automate the release cycle for you (https://github.com/marketplace/actions/pypi-publish)?
The general setup is to automatically push a release to PyPi whenever you push a git (version) tag to the repository, e.g.:

```bash
git tag 0.06
git push origin 0.06
```

If you're interested here is an (untested) yaml github action workflow file to do just that, which should probably work. You would need to put it under a .github/workflows folder in the repository and add a `pypi_password` secret to your repository configuration:

```yaml
name: "deploy-pyvan-to-pypi"

on: [push]

jobs:
  build_and_publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    name: Build and publish pyvan to PyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pep517
      run: >-
        python -m
        pip install
        pep517
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        pep517.build
        --source
        --binary
        --out-dir dist/
        .
    - name: Publish pyvan to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
```

Of course, beforehand you'll still need to adjust the version numbers manually in the `setup.py`. However, since you're using [semantic versioning](https://semver.org/), you might want to take a look at using [bump2version](https://pypi.org/project/bump2version/) for this, to change all the version numbers across an entire repository.
